name: Supabase Backup

on:
  schedule:
    - cron: '0 2 * * *' # Every day at 2am UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install pg_dump
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Run backup service
        working-directory: apps/supabase-backup
        env:
          DROPBOX_TOKEN: ${{ secrets.DROPBOX_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          npm run build
          node dist/index.js
